module ActiveRecord #:nodoc:
  module ConnectionAdapters #:nodoc:
    module OracleEnhancedReservedWords #:nodoc:

      RESERVED_WORDS = {
        "ACCESS" => true,
        "ADD" => true,
        "ALL" => true,
        "ALTER" => true,
        "AND" => true,
        "ANY" => true,
        "AS" => true,
        "ASC" => true,
        "AUDIT" => true,
        "BETWEEN" => true,
        "BY" => true,
        "CHAR" => true,
        "CHECK" => true,
        "CLUSTER" => true,
        "COLUMN" => true,
        "COMMENT" => true,
        "COMPRESS" => true,
        "CONNECT" => true,
        "CREATE" => true,
        "CURRENT" => true,
        "DATE" => true,
        "DECIMAL" => true,
        "DEFAULT" => true,
        "DELETE" => true,
        "DESC" => true,
        "DISTINCT" => true,
        "DROP" => true,
        "ELSE" => true,
        "EXCLUSIVE" => true,
        "EXISTS" => true,
        "FILE" => true,
        "FLOAT" => true,
        "FOR" => true,
        "FROM" => true,
        "GRANT" => true,
        "GROUP" => true,
        "HAVING" => true,
        "IDENTIFIED" => true,
        "IMMEDIATE" => true,
        "IN" => true,
        "INCREMENT" => true,
        "INDEX" => true,
        "INITIAL" => true,
        "INSERT" => true,
        "INTEGER" => true,
        "INTERSECT" => true,
        "INTO" => true,
        "IS" => true,
        "LEVEL" => true,
        "LIKE" => true,
        "LOCK" => true,
        "LONG" => true,
        "MAXEXTENTS" => true,
        "MINUS" => true,
        "MLSLABEL" => true,
        "MODE" => true,
        "MODIFY" => true,
        "NOAUDIT" => true,
        "NOCOMPRESS" => true,
        "NOT" => true,
        "NOWAIT" => true,
        "NULL" => true,
        "NUMBER" => true,
        "OF" => true,
        "OFFLINE" => true,
        "ON" => true,
        "ONLINE" => true,
        "OPTION" => true,
        "OR" => true,
        "ORDER" => true,
        "PCTFREE" => true,
        "PRIOR" => true,
        "PRIVILEGES" => true,
        "PUBLIC" => true,
        "RAW" => true,
        "RENAME" => true,
        "RESOURCE" => true,
        "REVOKE" => true,
        "ROW" => true,
        "ROWID" => true,
        "ROWNUM" => true,
        "ROWS" => true,
        "SELECT" => true,
        "SESSION" => true,
        "SET" => true,
        "SHARE" => true,
        "SIZE" => true,
        "SMALLINT" => true,
        "START" => true,
        "SUCCESSFUL" => true,
        "SYNONYM" => true,
        "SYSDATE" => true,
        "TABLE" => true,
        "THEN" => true,
        "TO" => true,
        "TRIGGER" => true,
        "UID" => true,
        "UNION" => true,
        "UNIQUE" => true,
        "UPDATE" => true,
        "USER" => true,
        "VALIDATE" => true,
        "VALUES" => true,
        "VARCHAR" => true,
        "VARCHAR2" => true,
        "VIEW" => true,
        "WHENEVER" => true,
        "WHERE" => true,
        "WITH" => true
      }

      def quote_oracle_reserved_words(name)
        RESERVED_WORDS[name.to_s.upcase].nil? ? name : "\"#{name}\""
      end
    end
  end
end

ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.class_eval do
  include ActiveRecord::ConnectionAdapters::OracleEnhancedReservedWords
end
