# frozen_string_literal: true

describe "identity primary keys" do
  include SchemaSpecHelper

  before(:all) do
    ActiveRecord::Base.establish_connection(CONNECTION_PARAMS)
    @conn = ActiveRecord::Base.lease_connection
    @oracle12c_or_higher = @conn.database_version.first >= 12
  end

  after(:each) do
    ActiveRecord::Migration.suppress_messages do
      schema_define do
        drop_table :test_identity_pks, if_exists: true
      end
    end
    @conn.schema_cache.clear!
  end

  def sequence_exists?(name)
    @conn.select_value(<<~SQL.squish, "SCHEMA").present?
      SELECT 1 FROM user_sequences WHERE sequence_name = '#{name.to_s.upcase}'
    SQL
  end

  def identity_column_exists?(table_name, column_name)
    return false unless @conn.supports_identity_columns?
    @conn.select_value(<<~SQL.squish, "SCHEMA").present?
      SELECT 1 FROM user_tab_identity_cols
       WHERE table_name = '#{table_name.to_s.upcase}'
         AND column_name = '#{column_name.to_s.upcase}'
    SQL
  end

  describe "adapter capability methods" do
    it "reports supports_identity_columns? based on database_version" do
      expect(@conn.supports_identity_columns?).to eq(@oracle12c_or_higher)
    end
  end

  describe "without identity: option (sequence-backed primary key)" do
    it "creates a sequence-backed primary key" do
      schema_define do
        create_table :test_identity_pks do |t|
          t.string :name
        end
      end

      expect(identity_column_exists?(:test_identity_pks, :id)).to be false
      expect(sequence_exists?(:test_identity_pks_seq)).to be true
      expect(@conn.prefetch_primary_key?(:test_identity_pks)).to be true
    end

    it "treats identity: false the same as the default" do
      schema_define do
        create_table :test_identity_pks, identity: false do |t|
          t.string :name
        end
      end

      expect(identity_column_exists?(:test_identity_pks, :id)).to be false
      expect(sequence_exists?(:test_identity_pks_seq)).to be true
    end
  end

  describe "with identity: true on Oracle 12.1+" do
    before do
      skip "requires Oracle 12.1+" unless @oracle12c_or_higher
    end

    it "creates a GENERATED BY DEFAULT AS IDENTITY column and no sequence" do
      schema_define do
        create_table :test_identity_pks, identity: true do |t|
          t.string :name
        end
      end

      expect(identity_column_exists?(:test_identity_pks, :id)).to be true
      expect(sequence_exists?(:test_identity_pks_seq)).to be false
    end

    it "skips prefetch_primary_key? for identity tables" do
      schema_define do
        create_table :test_identity_pks, identity: true do |t|
          t.string :name
        end
      end

      expect(@conn.prefetch_primary_key?(:test_identity_pks)).to be false
    end

    it "allows inserting rows without supplying id" do
      schema_define do
        create_table :test_identity_pks, identity: true do |t|
          t.string :name
        end
      end
      klass = Class.new(ActiveRecord::Base) { self.table_name = "test_identity_pks" }

      row = klass.create!(name: "alpha")
      expect(row.id).to be_a(Integer)
      expect(row.id).to be > 0
    end

    it "allows inserting rows with an explicit id (DEFAULT, not ALWAYS)" do
      schema_define do
        create_table :test_identity_pks, identity: true do |t|
          t.string :name
        end
      end
      klass = Class.new(ActiveRecord::Base) { self.table_name = "test_identity_pks" }

      row = klass.create!(id: 42, name: "bravo")
      expect(row.id).to eq(42)
    end
  end

  describe "with identity: true on Oracle below 12.1" do
    before do
      skip "applies only to Oracle versions before 12.1" if @oracle12c_or_higher
    end

    it "raises ArgumentError" do
      expect {
        @conn.create_table :test_identity_pks, identity: true, force: true do |t|
          t.string :name
        end
      }.to raise_error(ArgumentError, /Oracle Database 12\.1 or higher/)
    end
  end

  describe "add_column with identity: true" do
    before do
      skip "requires Oracle 12.1+" unless @oracle12c_or_higher
    end

    it "raises ArgumentError" do
      schema_define do
        create_table :test_identity_pks, id: false do |t|
          t.string :name
        end
      end

      expect {
        @conn.add_column :test_identity_pks, :id, :primary_key, identity: true
      }.to raise_error(ArgumentError, /not supported on `add_column`/)
    end
  end

  describe "prefetch_primary_key? cache invalidation" do
    before do
      skip "requires Oracle 12.1+" unless @oracle12c_or_higher
    end

    it "is invalidated when an identity table is dropped and recreated as sequence-backed" do
      schema_define do
        create_table :test_identity_pks, identity: true do |t|
          t.string :name
        end
      end
      expect(@conn.prefetch_primary_key?(:test_identity_pks)).to be false

      schema_define do
        drop_table :test_identity_pks
        create_table :test_identity_pks do |t|
          t.string :name
        end
      end
      expect(@conn.prefetch_primary_key?(:test_identity_pks)).to be true
    end

    it "is invalidated when a sequence-backed table is dropped and recreated as identity" do
      schema_define do
        create_table :test_identity_pks do |t|
          t.string :name
        end
      end
      expect(@conn.prefetch_primary_key?(:test_identity_pks)).to be true

      schema_define do
        drop_table :test_identity_pks
        create_table :test_identity_pks, identity: true do |t|
          t.string :name
        end
      end
      expect(@conn.prefetch_primary_key?(:test_identity_pks)).to be false
    end

    it "is invalidated when an identity table is renamed and a sequence-backed table reuses the old name" do
      schema_define do
        create_table :test_identity_pks, identity: true do |t|
          t.string :name
        end
      end
      expect(@conn.prefetch_primary_key?(:test_identity_pks)).to be false

      schema_define do
        rename_table :test_identity_pks, :test_identity_pks_renamed
        create_table :test_identity_pks do |t|
          t.string :name
        end
      end
      expect(@conn.prefetch_primary_key?(:test_identity_pks)).to be true
    ensure
      schema_define do
        drop_table :test_identity_pks_renamed, if_exists: true
      end
    end
  end

  describe "with a non-primary-key identity column" do
    before do
      skip "requires Oracle 12.1+" unless @oracle12c_or_higher
    end

    it "still reports prefetch_primary_key? for the sequence-backed primary key" do
      schema_define do
        create_table :test_identity_pks do |t|
          t.string :name
        end
      end
      @conn.execute "ALTER TABLE test_identity_pks ADD ext_id NUMBER GENERATED BY DEFAULT AS IDENTITY"

      expect(identity_column_exists?(:test_identity_pks, :ext_id)).to be true
      expect(identity_column_exists?(:test_identity_pks, :id)).to be false
      expect(@conn.prefetch_primary_key?(:test_identity_pks)).to be true
    end
  end

  describe "invalid identity: true combinations" do
    before do
      skip "requires Oracle 12.1+" unless @oracle12c_or_higher
    end

    it "raises when combined with id: false" do
      expect {
        @conn.create_table :test_identity_pks, identity: true, id: false, force: true do |t|
          t.string :name
        end
      }.to raise_error(ArgumentError, /requires `id: :primary_key`/)
    end

    it "raises when combined with id: :integer" do
      expect {
        @conn.create_table :test_identity_pks, identity: true, id: :integer, force: true do |t|
          t.string :name
        end
      }.to raise_error(ArgumentError, /requires `id: :primary_key`/)
    end

    it "raises when combined with id: :uuid" do
      expect {
        @conn.create_table :test_identity_pks, identity: true, id: :uuid, force: true do |t|
          t.string :name
        end
      }.to raise_error(ArgumentError, /requires `id: :primary_key`/)
    end

    it "raises when combined with a composite primary key" do
      expect {
        @conn.create_table :test_identity_pks, identity: true, primary_key: [:a, :b], force: true do |t|
          t.string :a
          t.string :b
        end
      }.to raise_error(ArgumentError, /composite primary key/)
    end
  end

  describe "schema_dumper roundtrip" do
    before do
      skip "requires Oracle 12.1+" unless @oracle12c_or_higher
    end

    it "emits identity: true for identity tables" do
      schema_define do
        create_table :test_identity_pks, identity: true do |t|
          t.string :name
        end
      end

      stream = StringIO.new
      ActiveRecord::SchemaDumper.ignore_tables = @conn.data_sources - ["test_identity_pks"]
      ActiveRecord::SchemaDumper.dump(ActiveRecord::Base.connection_pool, stream)
      ActiveRecord::SchemaDumper.ignore_tables = []

      expect(stream.string).to include('create_table "test_identity_pks"')
      expect(stream.string).to include("identity: true")
    end

    it "does not emit identity: true for sequence-backed tables" do
      schema_define do
        create_table :test_identity_pks do |t|
          t.string :name
        end
      end

      stream = StringIO.new
      ActiveRecord::SchemaDumper.ignore_tables = @conn.data_sources - ["test_identity_pks"]
      ActiveRecord::SchemaDumper.dump(ActiveRecord::Base.connection_pool, stream)
      ActiveRecord::SchemaDumper.ignore_tables = []

      expect(stream.string).to include('create_table "test_identity_pks"')
      expect(stream.string).not_to include("identity: true")
    end
  end
end
