# frozen_string_literal: true

require "active_record/fixtures"
require "tmpdir"

RSpec.describe "OracleEnhancedAdapter sequence reset" do
  include SchemaSpecHelper

  before(:all) do
    ActiveRecord::Base.establish_connection(CONNECTION_PARAMS)
    @conn = ActiveRecord::Base.lease_connection
  end

  after(:each) do
    ActiveRecord::Migration.suppress_messages do
      schema_define do
        drop_table :test_sequence_resets, if_exists: true
        drop_table :test_sequence_resets2, if_exists: true
      end
    end
    ActiveRecord::FixtureSet.reset_cache
    @conn.schema_cache.clear!
  end

  def create_test_table(name = :test_sequence_resets, **options)
    schema_define do
      create_table name, identity: false, **options do |t|
        t.string :title
      end
    end
  end

  def insert_ids(table, ids)
    ids.each { |id| @conn.execute("INSERT INTO #{table} (id, title) VALUES (#{id}, 'x')") }
  end

  def next_sequence_value(sequence)
    @conn.select_value("SELECT #{sequence}.NEXTVAL FROM dual")
  end

  def identity_attributes(table)
    @conn.select_one(<<~SQL.squish)
      SELECT i.generation_type, i.identity_options, c.default_on_null
        FROM user_tab_identity_cols i
        JOIN user_tab_columns c ON c.table_name = i.table_name AND c.column_name = i.column_name
       WHERE i.table_name = '#{table.to_s.upcase}'
    SQL
  end

  describe "after loading fixtures" do
    def load_fixtures(table)
      Dir.mktmpdir do |dir|
        File.write(File.join(dir, "#{table}.yml"), <<~YAML)
          one:
            id: 1
            title: one
          two:
            id: 2
            title: two
          three:
            id: 3
            title: three
        YAML
        ActiveRecord::FixtureSet.create_fixtures(dir, table.to_s)
      end
    end

    let(:model) do
      Class.new(ActiveRecord::Base) { self.table_name = "test_sequence_resets" }
    end

    it "continues a sequence-backed primary key after the fixture ids" do
      create_test_table
      load_fixtures(:test_sequence_resets)

      expect(model.create!(title: "new").id).to eq(4)
    end

    it "continues an identity primary key after the fixture ids" do
      skip "requires Oracle 12.1+" unless @conn.supports_identity_columns?
      create_test_table(identity: true)
      load_fixtures(:test_sequence_resets)

      expect(model.create!(title: "new").id).to eq(4)
    end
  end

  describe "#reset_pk_sequence!" do
    it "sets the next value to the maximum primary key plus one" do
      create_test_table
      insert_ids(:test_sequence_resets, [1, 2, 3])

      @conn.reset_pk_sequence!("test_sequence_resets")

      expect(next_sequence_value(:test_sequence_resets_seq)).to eq(4)
    end

    it "moves a sequence that is ahead of the table back to the maximum primary key plus one" do
      create_test_table
      insert_ids(:test_sequence_resets, [1, 2, 3])
      10.times { next_sequence_value(:test_sequence_resets_seq) }

      @conn.reset_pk_sequence!("test_sequence_resets")

      expect(next_sequence_value(:test_sequence_resets_seq)).to eq(4)
    end

    it "keeps the sequence attributes and grants" do
      skip "requires Oracle 18c+" unless @conn.database_version >= "18"
      create_test_table
      @conn.execute("ALTER SEQUENCE test_sequence_resets_seq INCREMENT BY 5 CACHE 7")
      @conn.execute("GRANT SELECT ON test_sequence_resets_seq TO #{DATABASE_SCHEMA}")
      insert_ids(:test_sequence_resets, [1, 2, 3])

      @conn.reset_pk_sequence!("test_sequence_resets")

      attributes = @conn.select_one(<<~SQL.squish)
        SELECT increment_by, cache_size FROM user_sequences WHERE sequence_name = 'TEST_SEQUENCE_RESETS_SEQ'
      SQL
      expect(attributes).to eq("increment_by" => 5, "cache_size" => 7)
      expect(@conn.select_value(<<~SQL.squish)).to eq("SELECT")
        SELECT privilege FROM user_tab_privs_made
         WHERE table_name = 'TEST_SEQUENCE_RESETS_SEQ' AND grantee = '#{DATABASE_SCHEMA.upcase}'
      SQL
      expect(next_sequence_value(:test_sequence_resets_seq)).to eq(4)
    end

    it "keeps the identity generation type and options" do
      skip "requires Oracle 12.1+" unless @conn.supports_identity_columns?
      @conn.execute(<<~SQL.squish)
        CREATE TABLE test_sequence_resets (
          id NUMBER(38) GENERATED BY DEFAULT ON NULL AS IDENTITY (INCREMENT BY 5 CACHE 7) PRIMARY KEY,
          title VARCHAR2(255)
        )
      SQL
      insert_ids(:test_sequence_resets, [1, 2, 3])

      @conn.reset_pk_sequence!("test_sequence_resets")

      attributes = identity_attributes(:test_sequence_resets)
      expect(attributes["generation_type"]).to eq("BY DEFAULT")
      expect(attributes["default_on_null"]).to eq("YES")
      expect(attributes["identity_options"]).to include("INCREMENT BY: 5", "CACHE_SIZE: 7")
      @conn.execute("INSERT INTO test_sequence_resets (title) VALUES ('new')")
      expect(@conn.select_value("SELECT MAX(id) FROM test_sequence_resets")).to eq(4)
    end

    it "keeps an identity generated always" do
      skip "requires Oracle 12.1+" unless @conn.supports_identity_columns?
      @conn.execute(<<~SQL.squish)
        CREATE TABLE test_sequence_resets (
          id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
          title VARCHAR2(255)
        )
      SQL
      3.times { @conn.execute("INSERT INTO test_sequence_resets (title) VALUES ('x')") }

      @conn.reset_pk_sequence!("test_sequence_resets")

      expect(identity_attributes(:test_sequence_resets)["generation_type"]).to eq("ALWAYS")
    end
  end

  describe "a primary key without a sequence" do
    it "is skipped" do
      schema_define do
        create_table :test_sequence_resets, id: :string do |t|
          t.string :title
        end
      end
      @conn.execute("INSERT INTO test_sequence_resets (id, title) VALUES ('a', 'x')")

      expect { @conn.reset_pk_sequence!("test_sequence_resets") }.not_to raise_error
    end
  end

  describe "#reset_column_sequences!" do
    it "resets the sequences of several tables" do
      create_test_table(:test_sequence_resets)
      create_test_table(:test_sequence_resets2)
      insert_ids(:test_sequence_resets, [1, 2, 3])
      insert_ids(:test_sequence_resets2, [10, 20])

      @conn.reset_column_sequences!([["test_sequence_resets"], ["test_sequence_resets2"]])

      expect(next_sequence_value(:test_sequence_resets_seq)).to eq(4)
      expect(next_sequence_value(:test_sequence_resets2_seq)).to eq(21)
    end
  end
end
