name: Linting
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  yamllint:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    name: Yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          rubygems: latest
      - name: Yamllint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
